# Nixpacks configuration for Eliza Agent Backend
# This deploys the main Eliza agent service

[variables]
NODE_VERSION = "22.11.0"
PNPM_VERSION = "9.12.3"
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@$PNPM_VERSION --activate",
    "pnpm config set store-dir ~/.pnpm-store",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
    "pnpm build"
]

[start]
cmd = "pnpm start"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3
