# Minimal Nixpacks configuration - fixes Docker Hub issues
# This uses Railway's default Node.js environment

[phases.install]
cmds = [
    "npm install -g pnpm@latest",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
    "pnpm build"
]

[start]
cmd = "pnpm start"

[variables.environment]
NODE_ENV = "production"
PORT = "3000"
