# Nixpacks configuration for Eliza Client Frontend
# This deploys the React/Vite client application

[variables]
NODE_VERSION = "22.11.0"
PNPM_VERSION = "9.12.3"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@$PNPM_VERSION --activate",
    "pnpm config set store-dir ~/.pnpm-store",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
    "pnpm run build"
]

[start]
cmd = "pnpm run preview"

[variables.environment]
NODE_ENV = "production"
PNPM_HOME = "/pnpm"
PATH = "$PNPM_HOME:$PATH"